apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-config
  namespace: www
  labels:
    app: pi-hole
data:
  05-custom.conf: |-
    server=/local/192.168.1.254
    address=/.cminion.cf/192.168.1.33
